config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'

  resources :tasks

  resources :rooms do
    resources :lists
  end


  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end


  get "/pages", to: 'pages#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room, optional: true
  has_many :tasks, inverse_of: :list

  validates :title, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  validates :title, presence: true
  belongs_to :user

  has_many :lists, inverse_of: :room
  has_many :tasks, through: :lists
  accepts_nested_attributes_for :lists, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :tasks
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :list, optional: true
  belongs_to :room, optional: true

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms
  has_many :lists, through: :rooms

  validates :email, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    rooms_path
  end




end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @room = Room.find(params[:id])
    @list = @room.lists.all
  end

  def create
    @room = Room.find(params[:room_id])
    @list = @room.lists.build(list_params)
    if @list.save
      redirect_to rooms_path(@room, @list)
    else
      render :index
    end
  end

  def show
    @list = List.find(params[:list_id])
  end

  private

  def list_params
    params.require(:list).permit(:title, :room_id, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


  def index
    @room = current_user.rooms.new
    @rooms = Room.all
  end

  def create
    @room = Room.find(params[:room_id])
    @room = @room.lists.build(room_params)
    if @room.save
      redirect_to rooms_path(@room)
    else
      render :index
    end
  end

  def show
    @room = Room.find(params[:id])
    @list = @room.lists.build
  end


  private

  def room_params
    params.require(:room).permit(:title, :user_id, lists_attributes: [:id, :list_title, :_destroy])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all 
  end

  def show
    @task = Task.find(params[:id])
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/lists/_list_card.html.erb
<!-- <div class="col-md-4 room-col"> -->
  <!-- <#%= link_to(@room.lists, class: "room-card") do %> -->
    <!-- <h4><#%= list.title %></h4> -->
  <!-- <#% end %> -->
<!-- </div> -->

app/views/lists/index.html.erb
<main class="container home">

  <div class="col-md-1 mr-auto">
    <button id="new-room-button" class="btn btn-primary mr-auto">New</button>
    <div id="new-room-popover" class="room-popover is-hidden">
      <div class="form-group">
        <%= form_for([@room, @list]) do |f| %>
          <%= f.text_field :title, class: "form-control", id: "room-title-input", placeholder:"Chore List Title", autoFocus: true %>
       </div>
          <%= f.submit "Save", class: "btn btn-success" %>
        <button id="cancel-room-popover" class="btn btn-secondary">Cancel</button>
        <% end %>
      </div>
    </div>

        <h3 class="text-center static-header">Chores</h3>


    <div class="row">
      <% @room.lists.each do |list| %>

      <div class="col-md-4 feature-col">
        <div class="chore-feature-card">
          <section class="card-body">
            <div class="card-body-content">
              <object class="card-icon">
                <article class="chorelist">
                  <h3 class="chore-header"><%= list.title %></h3>
                    <ul class="chores-list">
                      <li class="chore">
                        <div class="checkbox">
                          <label class="checkbox-label checkbox-label-disabled">
                            <span class="checkbox-button"></span>
                        </label>
                          <span class="checkbox-content">Wipe down Counters</span>
                        </div>
                      </li><!-- chore-->
                    </ul>
                  </article>
                </object>
              </div>
            </section><!--card-body -->

          </div>
        </div>
        <% end %>

      </div>

    </main>

app/views/rooms/_chore_card.html.erb
<div class="col-md-4 feature-col">
  <a class="feature-card" href="<%= room_lists_path(@room) %>">
      <h4><%= title %></h4>
        <img src="<%= image_url(img_src) %>" alt="<%= img_alt %>"></img>
        <section class="card-body">
          <div class="card-body-content">
            <object class="card-icon">
              <article class="chorelist">
                <h3 class="list-header">Main List</h3>
                  <ul class="chores-remaining">
                    <li class="chore">
                      <!-- <div class="checkbox">
                        <label class="checkbox-label checkbox-label-disabled">
                          <span class="checkbox-button"></span>
                        </label>
                          <span class="checkbox-content">Wipe down Counters</span>
                        </div> -->
                      </li><!-- chore-->
                    </ul>
                  </article>
                </object>
              </div>
          <p><%= description %></p>
        </section><!--card-body -->
      </a>
    </div>

app/views/rooms/_list_card.html.erb
<div class="col-md-4 feature-col">
  <div class="feature-room-card">
  <h4><%= list.list_title %></h4>
        <section class="card-body">
          <div class="card-body-content">
            <object class="card-icon">
              <article class="chorelist">
                <div class="chorelist-actions">
                  <p>Let's organize our chore lists</p>
                  <p>Click the Room name to start your Chore Lists</p>
                    </div>
                  </div>
                </div>
                  <ul class="chores-remaining">
                    
                    <li class="chore"></li>
                    </ul>
                  </article>
                </object>
              </div>
        </section><!--card-body -->
      </div>
    </div>

app/views/rooms/_message_card.html.erb
<div class="col-md-4 feature-col">
    <a class="feature-card" href="<%= feature_link %>">
      <h4><%= title %></h4>
        <img src="<%= image_url(img_src) %>" alt="<%= img_alt %>"></img>
        <section class="card-body">
          <div class="card-body-content">
            <object class="card-icon">
              <article class="chorelist">
                <h3 class="list-header">Family Messaging</h3>
                  <ul class="chores-remaining">
                    <li class="chore">
                      <!-- <div class="checkbox">
                        <label class="checkbox-label checkbox-label-disabled">
                          <span class="checkbox-button"></span>
                        </label>
                          <span class="checkbox-content"></span>
                        </div> -->
                      </li><!-- chore-->
                    </ul>
                  </article>
                </object>
              </div>
          <p><%= description %></p>
        </section><!--card-body -->
      </a>
    </div>

app/views/rooms/_room_card.html.erb
<div class="col-md-4 room-col">
  <%= link_to(room, class: "room-card") do %>
    <h4><%= room.title %></h4>
  <% end %>
</div>

app/views/rooms/_schedule_card.html.erb
<div class="col-md-4 feature-col">
    <a class="feature-card" href="<%= feature_link %>">
      <h4><%= title %></h4>
        <img src="<%= image_url(img_src) %>" alt="<%= img_alt %>"></img>
        <section class="card-body">
          <div class="card-body-content">
            <object class="card-icon">
              <article class="chorelist">
                <h3 class="list-header">Family Schedule</h3>
                  <ul class="chores-remaining">
                    <li class="chore">
                      <!-- <div class="checkbox">
                        <label class="checkbox-label checkbox-label-disabled">
                          <span class="checkbox-button"></span>
                        </label>
                          <span class="checkbox-content"></span>
                        </div> -->
                      </li><!-- chore-->
                    </ul>
                  </article>
                </object>
              </div>
          <p><%= description %></p>
        </section><!--card-body -->
      </a>
    </div>

app/views/rooms/create.js.erb
var roomList = document.getElementById('room-list')
var roomPopover = document.getElementById('new-room-popover')
var roomTitleInput = document.getElementById('room-title-input')
var newRoom = '<%= excape_javascript(render "room_card.html", room: @room) %>'

var div = document.createElement('div')

div.innerHTML = newRoom

roomList.appendChild(div.firstChild)
roomPopover.classList.add('is-hidden')
roomTitleInput.value = ''

app/views/rooms/index.html.erb
<main class="container home">
  <div class="row home-header">
    <div class="col-md-1 mr-auto">
      <button id="new-room-button" class="btn btn-primary mr-auto">ADD Room</button>
      <div id="new-room-popover" class="room-popover is-hidden">
        <%= form_with(model: @room) do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control", id: "room-title-input", placeholder:"Name Your Room", autoFocus: true %>
        </div>
          <%= f.submit "Save", class: "btn btn-success" %>
        <button id="cancel-room-popover" class="btn btn-secondary">Cancel</button>
        <% end %>
      </div>
    </div>
      <div class="col-md-4">
        <h3 class="text-center header-for-rooms">Clean House</h3>
      </div>
      <div class="col-md-1 ml-auto">
      </div>
    </div>
    <div id="room-list" class="row home-rooms">
      <% @rooms.each do |room| %>
        <%= render "room_card", room: room %>
      <% end %>
  </div>
</main>

app/views/rooms/show.html.erb
<main class="container home">
  <div class="row home-header">
    <div class="col-md-1 mr-auto">
      <button id="new-room-button" class="btn btn-primary mr-auto">ADD Room</button>
      <div id="new-room-popover" class="room-popover is-hidden">
        <%= form_for([@room, @list]) do |f| %>
        <div class="form-group">
          <%= f.text_field :list_title, class: "form-control", id: "room-title-input", placeholder:"Chore List", autoFocus: true %>
        </div>
          <%= f.submit "Save", class: "btn btn-success" %>
        <button id="cancel-room-popover" class="btn btn-secondary">Cancel</button>
        <% end %>
      </div>
    </div>
      <div class="col-md-4">
        <h3 class="text-center header-for-rooms"><%= @room.title %></h3>
      </div>
      <div class="col-md-1 ml-auto">
      </div>
    </div>
    <div id="room-list" class="row home-rooms">
      <% @room.lists.each do |list| %>
        <%= render "list_card", list: list %>
      <% end %>
  </div>
</main>

app/views/tasks/index.html.erb
<main class="container home">
  <div class="row home-header">
    <div class="col-md-1 mr-auto">
      <button id="new-room-button" class="btn btn-primary mr-auto">ADD CHORES</button>
      <div id="new-room-popover" class="room-popover is-hidden">

        <div class="form-group">
        </div>
        <button id="cancel-room-popover" class="btn btn-secondary">Cancel</button>
      </div>
    </div>
      <div class="col-md-4">
        <h3 class="text-center header-for-rooms">CHORES</h3>
      </div>
      <div class="col-md-1 ml-auto">
      </div>
    </div>



<div class="row">
  <div class="col-md-4 feature-col">
    <div class="chore-feature-card">
      <section class="card-body">
        <div class="card-body-content">
          <object class="card-icon">
            <article class="chorelist">
              <h3 class="chore-header"></h3>
                <ul class="chores-list">
                  <li class="chore">
                    <div class="checkbox">
                      <label class="checkbox-label checkbox-label-disabled">
                        <span class="checkbox-button"></span>
                    </label>
                      <span class="checkbox-content">Wipe down Counters</span>
                    </div>
                  </li><!-- chore-->
                </ul>
              </article>
            </object>
          </div>
        </section><!--card-body -->
      </div>
    </div>
  </div>
</main>