config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'

  resources :tasks

  resources :rooms do
    resources :lists
  end


  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end


  get "/pages", to: 'pages#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room, optional: true
  has_many :tasks, inverse_of: :list

  validates :title, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  validates :title, presence: true
  belongs_to :user

  has_many :lists, inverse_of: :room
  has_many :tasks, through: :lists
  accepts_nested_attributes_for :lists, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :tasks
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :list, optional: true
  belongs_to :room, optional: true

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms
  has_many :lists, through: :rooms

  validates :email, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    rooms_path
  end




end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @room = Room.find(params[:id])
    @list = @room.lists.all
  end

  def create
    @room = Room.find(params[:room_id])
    @list = @room.lists.build(list_params)
    if @list.save
      redirect_to rooms_path(@room, @list)
    else
      render :index
    end
  end

  def show
    @list = List.find(params[:list_id])
  end

  private

  def list_params
    params.require(:list).permit(:title, :room_id, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


  def index
    @room = current_user.rooms.new
    @rooms = Room.all
  end

  def create
    @room = Room.find(params[:room_id])
    @room = @room.lists.build(room_params)
    if @room.save
      redirect_to rooms_path(@room)
    else
      render :index
    end
  end

  def show
    @room = Room.find(params[:id])
    @list = @room.lists.build
  end


  private

  def room_params
    params.require(:room).permit(:title, :user_id, lists_attributes: [:id, :list_title, :_destroy])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all 
  end

  def show
    @task = Task.find(params[:id])
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg justify-content-between">
  <%= link_to 'LOGO', root_path, class: "navbar-brand" %>
  <ul class="navbar-nav align-self-center">

  </ul>
  <ul class="navbar-nav align-self-center">
    <% if user_signed_in? %>
    Welcome <strong><%= current_user.name %></strong>
      <li class="nav-item">
        <%= link_to "ACCOUNT", edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "SIGN UP", signup_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "LOG IN", login_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Project Home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>


    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_home.html.erb
<section class="home-hero">
  <!-- <div class="content content--bounded my-container"> -->
    <div class="home-hero-titles">
      <h1 class="home-hero-title">
        <span class="home-hero-title-main">
          Household Management Simplified
        </span>
      </h1>
      <h3 class="home-hero-subtitle">
        Let's boost your productivity
      </h3>
    </div><!-- home hero titles -->
    <div class="home-hero-frame">
     <!-- = image_tag("/assets/coverkitchens.png", alt: "image", class: "home-hero-screenshot" ) %> -->
    </div>
  <!-- content content bounded-->
  <div class="home-signUp">
    <h3 class="home-signUp-title">
      Sign up it's free!
    </h3>
    <%= link_to 'Sign Up', signup_path, class: 'welcome-button btn' %>
  </div>
</section>

app/views/pages/home.html.erb
<section class="home-hero">
  <div class="content content--bounded">
    <div class="home-hero-titles">
      <h1 class="home-hero-title">
        <span class="home-hero-title-main">
          Household Management Simplified
        </span>
      </h1>
      <h3 class="home-hero-subtitle">
        Let's boost your productivity
      </h3>
    </div><!-- home hero titles -->
    <div class="home-hero-frame">
      <%= image_tag("/assets/coverkitchen.jpg", alt: "image", class: "home-hero-screenshot" ) %>
    </div>
  </div><!-- content content bounded-->
  <div class="home-signUp">
    <h3 class="home-signUp-title">
      Sign up it's free!
    </h3>
    <%= link_to 'Sign Up', signup_path, class: 'welcome-button btn' %>
  </div>
</section>